'use strict';
const fs=require('fs'),vm=require('vm'),path=require('path'),crypto=require('crypto');
const ctx={console,crypto:crypto.webcrypto,window:null,navigator:{onLine:true},document:{},alert:()=>{}};ctx.window=ctx;vm.createContext(ctx);
vm.runInContext(fs.readFileSync(path.join(__dirname,'js/core/estado-global.js'),'utf8'),ctx);
const payload='<img src=x onerror="window.__xss=true">';
const escaped=ctx.escapeHtml(payload);
const ok=!escaped.includes('<img') && escaped.includes('&lt;img') && escaped.includes('&quot;');
console.log((ok?'OK  ':'FALHA ')+'escapeHtml impede injeção de tag/atributo no conteúdo dinâmico');
if(!ok) console.log(escaped);
process.exit(ok?0:1);
